spring:
  profiles:
    active:
    - dev
 
---
server:
  port: 8004
spring:
  profiles: dev
  application:
    name: microservicecloud-config-neuedu-dev
    
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-neuedu-test
